name: unit-test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'iosApp/**'

run-name: "unit-test by ${{ github.actor }}"

permissions: { }

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/actions/setup-java

      - name: Upload an event payload for EnricoMi/publish-unit-test-result-action
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: event-payload
          path: ${{ github.event_path }}

      - run: ./gradlew testDebugUnitTest --stacktrace

      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        if: always()
        with:
          name: test-reports
          path: |
            **/reports
